# Generated by Django 5.2.15 on 2026-06-10 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('message', models.TextField()),
                ('channel', models.CharField(max_length=50)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.segment')),
            ],
        ),
    ]
